version: '3.1'
services:
  
  dbpostgresql:
    image: postgres
    volumes:
      - posgresdocker-data:/var/lib/postgres 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Jamb1975
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usuariospost
volumes: 
  posgresdocker-data: